In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
%matplotlib inline

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/UNP C2C Assign 1 /iris.data") 

In [ ]:
df.columns= ["sepal length", "sepal width", "petal length", "petal width", "classs"]

In [ ]:
df

sepal length  sepal width  petal length  petal width  classs
0             4.9          3.0           1.4          0.2       0
1             4.7          3.2           1.3          0.2       0
2             4.6          3.1           1.5          0.2       0
3             5.0          3.6           1.4          0.2       0
4             5.4          3.9           1.7          0.4       0
..            ...          ...           ...          ...     ...
144           6.7          3.0           5.2          2.3       2
145           6.3          2.5           5.0          1.9       2
146           6.5          3.0           5.2          2.0       2
147           6.2          3.4           5.4          2.3       2
148           5.9          3.0           5.1          1.8       2

[149 rows x 5 columns]

In [ ]:
df.classs.unique()
#the outcome is categorical with three different outputs 

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
#checking missing vaulues
df.isnull().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
classs          0
dtype: int64

## logistic regression

In [ ]:
flower_numbers = {"classs" : {'Iris-setosa' :0, 'Iris-versicolor' :1, 'Iris-virginica' :2} }

In [ ]:
x=df[["sepal length", "sepal width", "petal length", "petal width"]].values
y=df[["classs"]].values

In [ ]:
df= df.replace(flower_numbers)

In [ ]:
x_train,x_test,y_train,y_test = sklearn.model_selection.train_test_split(x,y, test_size = 0.2, random_state =2)

In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression(random_state=0)

In [ ]:
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [ ]:
logmodel.score(x,y)

0.9865771812080537

In [ ]:
predicted=logmodel.predict(x)
predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
y_pred = logmodel.predict(x_test)
print(y_pred)

[2 0 0 0 2 0 2 0 2 2 0 1 2 0 2 2 0 1 2 2 1 1 1 1 0 0 1 1 0 0]


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[12  0  0]
 [ 0  8  1]
 [ 0  0  9]]
